export const FormsTypes= {
    SAVE_NAME_FORM:"@form/ SAVE_NAME_FORM",
    SAVE_PERSONAL_FORM: "@form/SAVE_PERSONAL_FORM",
    SAVE_ADDRESS_FORM: "@form/ SAVE_ADDRESS_FORM",

    GET_CAT_GALLERY:"@form/ GET_CAT_GALLERY",
    GET_CAT_GALLERY_SUCCESS:"@form/ GET_CAT_GALLERY_SUCCESS"
    
}